'\" t
.TH "HALT" "8" "" "systemd 231" "halt"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
halt, poweroff, reboot \- 停机、关机、重新启动
.SH "SYNOPSIS"
.HP \w'\fBhalt\fR\ 'u
\fBhalt\fR [OPTIONS...]
.HP \w'\fBpoweroff\fR\ 'u
\fBpoweroff\fR [OPTIONS...]
.HP \w'\fBreboot\fR\ 'u
\fBreboot\fR [OPTIONS...]
.SH "描述"
.PP
\fBhalt\fR,
\fBpoweroff\fR,
\fBreboot\fR
可以分别用于停机、关机、 重新启动
.SH "选项"
.PP
能够识别的命令行选项如下：
.PP
\fB\-\-help\fR
.RS 4
显示简短的帮助信息并退出。
.RE
.PP
\fB\-\-halt\fR
.RS 4
停机(关闭系统但是不切断电源)
.RE
.PP
\fB\-p\fR, \fB\-\-poweroff\fR
.RS 4
关机(关闭系统并且切断电源)
.RE
.PP
\fB\-\-reboot\fR
.RS 4
重新启动
.RE
.PP
\fB\-f\fR, \fB\-\-force\fR
.RS 4
强制立即停机/关机/重新启动， 而不与 init 进程通信。
.RE
.PP
\fB\-w\fR, \fB\-\-wtmp\-only\fR
.RS 4
仅向 wtmp 中写入一条关机记录， 而不实际执行关机动作。
.RE
.PP
\fB\-d\fR, \fB\-\-no\-wtmp\fR
.RS 4
不向 wtmp 中写入任何关机记录
.RE
.PP
\fB\-n\fR, \fB\-\-no\-sync\fR
.RS 4
在关机前不刷写磁盘缓存
.RE
.PP
\fB\-\-no\-wall\fR
.RS 4
在关机前不发送警告信息
.RE
.SH "退出状态"
.PP
返回值为 0 表示成功， 非零返回值表示失败代码。
.SH "注意"
.PP
这些命令仅仅是为了兼容传统的命令而存在
.SH "参见"
.PP
\fBsystemd\fR(1),
\fBsystemctl\fR(1),
\fBshutdown\fR(8),
\fBwall\fR(1)
