'\" t
.TH "NSS\-MYMACHINES" "8" "" "systemd 231" "nss-mymachines"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
nss-mymachines, libnss_mymachines.so.2 \- 提供了解析本地容器名称的功能
.SH "SYNOPSIS"
.PP
libnss_mymachines\&.so\&.2
.SH "描述"
.PP
\fBnss\-mymachines\fR
是一个
\fBglibc\fR(GNU C Library) NSS(Name Service Switch) 插件， 提供了本地容器名称的解析功能。
\fBsystemd-machined.service\fR(8)
服务 按照本地容器所属 scope 的顺序， 在这些本地容器的名称与其IP地址之间建立对应关系。 该功能仅可用于使用了网络名字空间(network namespace)的容器。
.PP
该模块还可以为使用了用户名字空间(user namespace)的容器提供解析 UID/GID 与用户名/组名之间对应关系的功能。
.PP
要激活NSS模块，可将
"mymachines"
添加到
/etc/nsswitch\&.conf
文件中以
"hosts:",
"passwd:",
"group:"
开头的行里面。
.PP
建议将
"mymachines"
放置在
/etc/nsswitch\&.conf
文件中 紧跟
"files"
或
"compat"
项之后，以确保在解析时，本地映射文件
/etc/hosts,
/etc/passwd,
/etc/group
仍为最优先， 同时又将其他解析方式(DNS之类)作为后备。
.SH "例子"
.PP
下面是一个正确开启了
\fBnss\-mymachines\fR
插件的
/etc/nsswitch\&.conf
文件的例子：
.sp
.if n \{\
.RS 4
.\}
.nf
passwd:         compat \fBmymachines\fR
group:          compat \fBmymachines\fR
shadow:         compat

hosts:          files \fBmymachines\fR resolve myhostname
networks:       files

protocols:      db files
services:       db files
ethers:         db files
rpc:            db files

netgroup:       nis
.fi
.if n \{\
.RE
.\}
.SH "参见"
.PP
\fBsystemd\fR(1),
\fBsystemd-machined.service\fR(8),
\fBnss-resolve\fR(8),
\fBnss-myhostname\fR(8),
\fBnsswitch.conf\fR(5),
\fBgetent\fR(1)
.\" manpages-zh translator: 金步国
.\" manpages-zh comment: 金步国作品集：http://www.jinbuguo.com
