'\" t
.TH "SYSTEMD\-QUOTACHECK\&.SERVICE" "8" "" "systemd 231" "systemd-quotacheck.service"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
systemd-quotacheck.service, systemd-quotacheck \- 文件系统配额检查
.SH "SYNOPSIS"
.PP
systemd\-quotacheck\&.service
.PP
/usr/lib/systemd/systemd\-quotacheck
.SH "描述"
.PP
systemd\-quotacheck\&.service
服务 可用于检查文件系统配额。在系统启动过程中，当挂载完所有必要的文件系统之后， 仅在确实存在至少一个开启了配额限制的文件系统的情况下， 该服务将运行一次。
.SH "内核引导选项"
.PP
systemd\-quotacheck
能够识别 下列内核引导选项：
.PP
\fIquotacheck\&.mode=\fR
.RS 4
表示操作模式，有效值为
"auto",
"force",
"skip"
之一。 默认值
"auto"
表示 仅在确实存在开启了配额限制的文件系统的情况下， 才进行文件系统配额检查。
"force"
表示无条件的对所有文件系统强制进行 配额检查。"skip"
表示无条件的强制跳过所有文件系统的配额检查。
.RE
.SH "参见"
.PP
\fBsystemd\fR(1),
\fBquotacheck\fR(8),
\fBsystemd-fsck@.service\fR(8)
.\" manpages-zh translator: 金步国
.\" manpages-zh comment: 金步国作品集：http://www.jinbuguo.com
