'\" t
.TH "SYSTEMD\-MACHINE\-ID\-SETUP" "1" "" "systemd 231" "systemd-machine-id-setup"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
systemd-machine-id-setup \- 初始化 /etc/machine\-id 文件
.SH "SYNOPSIS"
.HP \w'\fBsystemd\-machine\-id\-setup\fR\ 'u
\fBsystemd\-machine\-id\-setup\fR
.SH "描述"
.PP
\fBsystemd\-machine\-id\-setup\fR
可被操作系统安装程序用来初始化
/etc/machine\-id
中的"machine ID"值， 可以设为一个指定值，也可以设为一个随机生成的值。详见
\fBmachine-id\fR(5)
手册。
.PP
如果没有明确使用
\fB\-\-commit\fR
选项并且
/etc/machine\-id
不存在或其中的值不合格， 那么将初始化一个新的"machined ID"。 此新"machine ID"将依次使用下列方法获得：
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
如果已经存在一个有效的 D\-Bus "machine ID"， 那么就使用此 D\-Bus "machine ID" 来初始化
/etc/machine\-id
文件。
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  2." 4.2
.\}
如果运行在已经配置了UUID(通过
\fB\-uuid\fR
选项)的KVM虚拟机中， 那么就使用此UUID来初始化 /etc/machine\-id 文件。 KVM虚拟机的创建者 必须确保UUID的唯一性。
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 3.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  3." 4.2
.\}
如果运行在已经配置了UUID的Linux容器中， 那么就使用此UUID来初始化 /etc/machine\-id 文件。 详见
\m[blue]\fBContainer Interface\fR\m[]\&\s-2\u[1]\d\s+2
文档。
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 4.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  4." 4.2
.\}
如果上述方法都不可用， 那么随机生成一个新的"machine ID"来初始化 /etc/machine\-id 文件。
.RE
.PP
可以使用
\fB\-\-commit\fR
选项将新生成的临时"machine ID"写入到磁盘中永久保存。 详见下文。
.PP
可以使用
\fBsystemd-firstboot\fR(1)
初始化已挂载(但未启动)的系统镜像的"machine ID"。
.SH "选项"
.PP
能够识别的命令行选项如下：
.PP
\fB\-\-root=\fR\fB\fIroot\fR\fR
.RS 4
指定一个"根目录"， 包括配置文件在内的所有路径都将加上
\fIroot\fR
前缀，包括
/etc/machine\-id
自身。
.RE
.PP
\fB\-\-commit\fR
.RS 4
将生成的临时"machine ID"写入到磁盘中永久保存。 所谓"临时"的意思是指在 系统启动的早期绑定挂载的
"tmpfs"
文件系统中的
/etc/machine\-id
文件。 这可能是由于在系统启动的早期，
/etc
依然处于只读状态 并且其中并不包含合格的 /etc/machine\-id 文件。
.sp
如果
/etc/machine\-id
未被绑定挂载到
"tmpfs"
文件系统， 或者
/etc
处于只读状态， 那么此选项将不执行任何操作。 否则，此命令将会把临时生成的"machine ID"写入到磁盘中， 然后卸载
/etc/machine\-id
所在的文件系统， 以确保"machine ID"确实被永久保存。
.sp
此选项主要被系统启动早期的
\fBsystemd-machine-id-commit.service\fR(8)
使用。
.RE
.PP
\fB\-\-print\fR
.RS 4
操作完成之后打印出"machine ID"的值
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
显示简短的帮助信息并退出。
.RE
.PP
\fB\-\-version\fR
.RS 4
显示简短的版本信息并退出。
.RE
.SH "退出状态"
.PP
返回值为 0 表示成功， 非零返回值表示失败代码。
.SH "参见"
.PP
\fBsystemd\fR(1),
\fBmachine-id\fR(5),
\fBsystemd-machine-id-commit.service\fR(8),
\fBdbus-uuidgen\fR(1),
\fBsystemd-firstboot\fR(1)
.SH "NOTES"
.IP " 1." 4
Container Interface
.RS 4
\%http://www.freedesktop.org/wiki/Software/systemd/ContainerInterface
.RE
.\" manpages-zh translator: 金步国
.\" manpages-zh comment: 金步国作品集：http://www.jinbuguo.com
