'\" t
.TH "SYSTEMD\-PATH" "1" "" "systemd 231" "systemd-path"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
systemd-path \- 列出各种系统路径与用户路径
.SH "SYNOPSIS"
.HP \w'\fBsystemd\-path\ \fR\fB[OPTIONS...]\fR\fB\ \fR\fB[NAME...]\fR\ 'u
\fBsystemd\-path \fR\fB[OPTIONS...]\fR\fB \fR\fB[NAME...]\fR
.SH "描述"
.PP
\fBsystemd\-path\fR
用于列出各种系统路径与用户路径。
\fBfile-hierarchy\fR(7)
中对各种路径的用途有详细的说明。
.PP
当未指定任何
[NAME...]
参数的时候，将会列出各种用途的路径的当前值。 当指定了至少一个
[NAME...]
参数的时候， 将仅显示指定用途的路径的当前值。 注意，那些名称以
"search\-"
开头的用途， 并不对应着一个单独的路径，而是对应着一组冒号分隔的搜索路径列表， 列表中路径的顺序也是路径的搜索顺序。
.SH "选项"
.PP
能够识别的命令行选项如下：
.PP
\fB\-\-suffix=\fR
.RS 4
在所有路径的末尾加上 指定的后缀字符串。
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
显示简短的帮助信息并退出。
.RE
.PP
\fB\-\-version\fR
.RS 4
显示简短的版本信息并退出。
.RE
.SH "退出状态"
.PP
返回值为 0 表示成功， 非零返回值表示失败代码。
.SH "参见"
.PP
\fBsystemd\fR(1),
\fBfile-hierarchy\fR(7)
.\" manpages-zh translator: 金步国
.\" manpages-zh comment: 金步国作品集：http://www.jinbuguo.com
