.TH WALL "1" "2013年8月" "util-linux" "用户命令"

.SH 名称
wall -- 向所有人发送消息

.SH 总览
.B wall
.RB [ \-n ]
.RB [ \-t
.IR 超时时间 ]
.RB [ \-g
.IR 用户组 ]
.RI [ 消息内容 " | " 文件 ]
.SH 描述
.B wall
显示一条给定的
.IR 消息内容 ,
或是
.IR 给定文件
中的内容，或者程序标准输入的内容，将其显示在所有当前已登录用户的终端上。
该命令会自动将长于 79 字符的行进行折行。
短行将会使用空格填充到 79 字符的宽度。
该命令总会在每行末尾放置一个回车符和一个换行符。
.PP
只有超级用户才能写入选择拒绝接收消息的用户的终端上，
或是使用程序自动拒绝接收消息的用户终端上。
.PP
当程序调用者不是超级用户，且程序是设置用户 ID 或设置组 ID
的状态下时，从
.I 指定文件
读取消息的操作将会被拒绝。
.SH 选项
.TP
.BR \-n , " \-\-nobanner"
不显示抬头信息。
.TP
.BR \-t , " \-\-timeout " \fI超时时间\fR
在给定\fI超时\fR秒数后放弃写入终端的尝试。
\fI超时时间\fR必须是一个正整数。默认值是 300
秒，这个默认值是从调制解调器时代遗留下来的结果。
.TP
.BR \-g , " \-\-group " \fI用户组\fR
限制仅将消息发送给指定用户组的成员。参数可以是用户组名或 GID。
.TP
.BR \-V , " \-\-version"
显示版本信息并退出。
.TP
.BR \-h , " \-\-help"
显示帮助文本并退出。
.SH 备注
某些会话，例如 wdm，在
.BR utmp (5)
ut_type 数据的起始部分会记录一个 ':' 符号，这些用户会话不会收到
.BR wall
发来的消息。这么做是为了避免出现写入错误。
.SH 参见
.BR mesg (1),
.BR talk (1),
.BR write (1),
.BR shutdown (8)
.SH 历史
.B wall
命令在 AT&T UNIX 第 7 版中出现。
.SH 可用性
wall 命令是 util-linux 软件包的一部分，可以在
.UR https://\:www.kernel.org\:/pub\:/linux\:/utils\:/util-linux/
Linux 内核存档
.UE
中找到。
.\" manpages-zh translator: Boyuan Yang
.\" manpages-zh date: 2018-04-17
.\" manpages-zh orig-package: util-linux
