.\" info(5)
.\" $Id: info.5 5191 2013-02-23 00:11:18Z karl $
.\"
.\" Copyright 1998, 2005, 2011 Free Software Foundation, Inc.
.\"
.\" Copying and distribution of this file, with or without modification,
.\" are permitted in any medium withou royalty provided the copyright
.\" notice and this notice are preserved.
.\"
.de EX
.nf
.ft CW
.in +5
..
.de EE
.in -5
.ft R
.fi
..
.TH INFO 5 "GNU Info" "自由软件基金会"
.SH "名称"
info \- 易读的在线文档
.SH "描述"
Info 文件格式是一种易于解析的在线文档表示格式。它可以用
.I emacs(1)
和
.I info(1)
以及一些其他程序来阅读。
.PP
Info 文件通常创建自
.I texinfo(5)
源文件，使用
.IR makeinfo(1)
命令。但是，如果需要的话，也可以自行创建。
.PP
要查看 Texinfo 语言和相关工具的全面描述，请查看 Texinfo 手册（以 Texinfo 自身写成）。
最简单的，从 shell 中运行这个命令：
.EX
info texinfo
.EE
或者在 Emacs 中输入按键序列：
.EX
M-x info RET m texinfo RET
.EE
也可以把你带到那里。
.SH "获取"
http://www.gnu.org/software/texinfo/
.SH "报告错误"
将错误报告发送到 bug-texinfo@gnu.org，
一般的问题和讨论则发送到 help-texinfo@gnu.org。
.SH "参见"
info(1), install-info(1), makeinfo(1), texi2dvi(1),
.br
texindex(1).
.br
emacs(1), tex(1).
.br
texinfo(5).
