'\" t
.TH "LOCALTIME" "5" "" "systemd 231" "localtime"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
localtime \- 本地时区配置文件
.SH "SYNOPSIS"
.PP
/etc/localtime
\->
\&.\&./usr/share/zoneinfo/\&...
.SH "描述"
.PP
/etc/localtime
用于配置 全系统范围的时区，许多应用程序需要根据它 正确显示时间。它必须是一个 指向
/usr/share/zoneinfo/
目录中 某个时区文件(对于中华人民共和国来说应该是
"PRC")的软连接。 [译者注]很多人错误的将
"Asia/Shanghai"
当作中华人民共和国的时区， 但实际上
\m[blue]\fBAsia/Shanghai\fR\m[]\&\s-2\u[1]\d\s+2
是中华民国的"\m[blue]\fB中原时区\fR\m[]\&\s-2\u[2]\d\s+2"，遵守的是中华民国的时间规则， 并不能正确处理中华人民共和国在1986年到1991年采用夏时制期间的时间(可能会有一小时的偏差)。 当然，在处理1992年以后的时间上，两者是一致的。
.PP
因为本机时区是根据
/etc/localtime
所指向的目标文件确定的，所以
/etc/localtime
文件 必须是一个软连接，而不能是一个普通文件或硬连接。
.PP
可以通过
\fI$TZ\fR
环境变量来为个别的应用程序设置专用的时区。详见
\fBenviron\fR(7)
手册。
.PP
可以使用
\fBtimedatectl\fR(1)
在运行时更改时区的设置(也就是软连接的指向)。 可以使用
\fBsystemd-firstboot\fR(1)
初始化已挂载(但未启动)的系统镜像的时区设置。
.SH "参见"
.PP
\fBsystemd\fR(1),
\fBtzset\fR(3),
\fBlocaltime\fR(3),
\fBtimedatectl\fR(1),
\fBsystemd-timedated.service\fR(8),
\fBsystemd-firstboot\fR(1)
.SH "NOTES"
.IP " 1." 4
Asia/Shanghai
.RS 4
\%https://en.wikipedia.org/wiki/Asia/Shanghai
.RE
.IP " 2." 4
中原时区
.RS 4
\%https://zh.wikipedia.org/zh-cn/%E4%B8%AD%E5%9C%8B%E6%99%82%E5%8D%80
.RE
.\" manpages-zh translator: 金步国
.\" manpages-zh comment: 金步国作品集：http://www.jinbuguo.com
